// #pragma kernel CSUpdate

// #include "InstanceData.hlsl"

// StructuredBuffer<InstanceData> inputBuffer;
// RWStructuredBuffer<InstanceData> outputBuffer;

// float deltaTime;

// [numthreads(64,1,1)]
// void CSUpdate (uint3 id : SV_DispatchThreadID)
// {
//     uint i = id.x;
//     if (i >= inputBuffer.Length) return;

//     InstanceData d = inputBuffer[i];
//     if (d.active == 0) return;

//     d.position += d.velocity * deltaTime;

//     outputBuffer[i] = d;
// }

